In [62]:
import numpy as np
import pandas as pd 

from scipy import stats

In [66]:
path="/home/dexter/Documents/GitHub/3D-textures/assets/experimental_corrected_results.csv"
df = pd.read_csv(path)
path="/home/dexter/Documents/GitHub/3D-textures/assets/experimental_method_results.csv"
dft = pd.read_csv(path)


dft = dft[dft["Raw_Avg_Distance"] <= 0.005].copy()
df = df[df["Raw_Avg_Distance"] <= 0.005].copy()
print(dft.head())
df.head()

  Printer  Texture Test_Type Comparison  Raw_Avg_Distance  Std_Deviation
0       B        5         T     1 vs 2          0.000177       0.000127
1       B        5         T     1 vs 3          0.000158       0.000090
2       B        5         T     1 vs 4          0.000172       0.000110
3       B        5         T     1 vs 5          0.000285       0.000271
4       B        5         T     2 vs 1          0.000205       0.000112

  Printer  Texture Test_Type Comparison  Raw_Avg_Distance  Std_Deviation
0       E        2         T     1 vs 2          0.000243       0.000214
1       E        2         T     1 vs 3          0.000275       0.000228
2       E        2         T     1 vs 4          0.000353       0.000347
3       E        2         T     1 vs 5          0.000337       0.000270
4       E        2         T     2 vs 1          0.000503       0.000456

In [67]:
dft.loc[
            (dft["Printer"] == "E") &
            (dft["Texture"] == 3)
        ].copy()

    Printer  Texture Test_Type Comparison  Raw_Avg_Distance  Std_Deviation
160       E        3         T     1 vs 2          0.004263       0.081456
161       E        3         T     1 vs 3          0.001725       0.020348
162       E        3         T     1 vs 4          0.001543       0.019493
163       E        3         T     1 vs 5          0.001720       0.008324
164       E        3         T     2 vs 1          0.001443       0.006067
165       E        3         T     2 vs 3          0.001341       0.007694
166       E        3         T     2 vs 4          0.001295       0.004360
167       E        3         T     2 vs 5          0.001183       0.007285
171       E        3         T     3 vs 5          0.004621       0.065956
172       E        3         T     4 vs 1          0.004462       0.044013
176       E        3         T     5 vs 1          0.002928       0.020959
178       E        3         T     5 vs 3          0.003634       0.025570
179       E        3         T     5 vs 4          0.003873       0.043702

In [68]:
from scipy.stats import ttest_ind
import pandas as pd
pd.set_option('display.float_format', '{:.6f}'.format)
printers = ["E", "B", "R"]

print("Printer\t texture \t raw average \t raw std \t method average \t method std \t p-value \t n")

new_table = {
    "Printer": [],
    "Texture": [],
    "Raw AVG": [],
    "Raw STD": [],
    "Method AVG": [],
    "Method STD": [],
    "N": [],
    "N method": [],
    "T-test p-value": []
}

for j in range(3):
    for i in range(1, 7):

        # Raw data
        raw_result = df.loc[
            (df["Printer"] == printers[j]) &
            (df["Texture"] == i)
        ].copy()

        raw_data = raw_result["Raw_Avg_Distance"].dropna()

        avg_raw = raw_data.mean() * 10000
        std_raw = raw_data.std() * 10000
        n_raw = len(raw_data)

        # Method data
        method_result = dft.loc[
            (dft["Printer"] == printers[j]) &
            (dft["Texture"] == i)
        ].copy()

        method_data = method_result["Raw_Avg_Distance"].dropna()

        avg_method = method_data.mean() * 10000
        std_method = method_data.std() * 10000
        n_method = len(method_data)

        t_stat, p_two_sided = ttest_ind(
            raw_data,
            method_data,
            equal_var=False
        )

        if t_stat > 0:
            p_value = p_two_sided / 2
        else:
            p_value = 1 - (p_two_sided / 2)

        # Store results
        new_table["Printer"].append(printers[j])
        new_table["Texture"].append(i)

        new_table["Raw AVG"].append(avg_raw)
        new_table["Raw STD"].append(std_raw)

        new_table["Method AVG"].append(avg_method)
        new_table["Method STD"].append(std_method)

        new_table["N"].append(n_raw)
        new_table["N method"].append(n_method)

        new_table["T-test p-value"].append(p_value)


new_table = pd.DataFrame(new_table)

new_table

Printer	 texture 	 raw average 	 raw std 	 method average 	 method std 	 p-value 	 n

,Printer,Texture,Raw AVG,Raw STD,Method AVG,Method STD,N,N method,T-test p-value
0,E,1,4.104285,1.199180,1.908715,0.335883,20,20,0.000000
1,E,2,3.776725,1.149230,2.731070,1.403772,20,20,0.007059
2,E,3,3.357355,0.539673,26.176331,13.662273,20,13,0.999970
3,E,4,4.110815,0.897083,1.804530,0.346053,20,20,0.000000
4,E,5,4.583890,1.211352,2.004025,0.404304,20,20,0.000000
5,E,6,6.266950,2.284794,2.423695,1.253853,20,20,0.000000
6,B,1,2.787930,1.032770,1.899380,0.317494,20,20,0.000639
7,B,2,2.510240,0.458018,1.848845,0.931374,20,20,0.004083
8,B,3,2.776550,0.400182,1.950600,1.180156,20,20,0.003444
9,B,4,2.302920,0.391650,1.604930,0.346888,20,20,0.000000
10,B,5,2.405800,0.348062,1.875695,0.298052,20,20,0.000004
11,B,6,1.999570,0.297169,1.541265,0.372574,20,20,0.000062
12,R,1,2.827990,1.581708,2.009715,0.248975,20,20,0.016685
13,R,2,4.201765,1.795889,2.037845,0.953690,20,20,0.000025
14,R,3,2.648750,0.589854,2.054415,0.512289,20,20,0.000805
15,R,4,2.702758,0.442302,2.229230,0.567146,12,20,0.006862
16,R,5,2.394055,0.137492,2.213445,0.165019,20,20,0.000295
17,R,6,2.832900,0.403777,1.844010,0.900917,20,20,0.000065